spring:
  application:
    name: TechnicalAssignment

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true

  liquibase:
    enabled: true
    change-log: "classpath:/liquibase/changelog-master.yaml"
    default-schema: public

  thymeleaf:
    cache: false

server:
  port: ${SERVER_PORT}
